[[feeds]]
key = "scale_ai_blog"
name = "Scale AI Blog"
url = "https://scale.com/blog"


[[feeds]]
key = "meta_ai_blog"
name = "Meta AI Blog"
url = "https://ai.meta.com/blog"


# [[feeds]]
# key = "simon_willison_blog"
# name = "Simon Willison's Blog"
# url = "https://simonwillison.net/atom/everything/"
