[[feeds]]
key = "google_research_blog"
name = "Google Research Blog"
url = "https://research.google/blog/rss/"

[[feeds]]
key = "deepmind_blog"
name = "DeepMind Blog"
url = "https://deepmind.google/blog/rss.xml"

[[feeds]]
key = "openai_news"
name = "OpenAI News"
url = "https://openai.com/news/rss.xml"

[[feeds]]
key = "simon_willison_blog"
name = "Simon Willison's Blog"
url = "https://simonwillison.net/atom/everything/"


[[feeds]]
key = "daring_fireball"
name = "Daring Fireball"
url = "https://morss.it/https://daringfireball.net/"

[[feeds]]
key = "scale_ai_blog"
name = "Scale AI Blog"
url = "https://morss.it/:items=%7C%7C*[class=%CF%81th]/https://scale.com/blog"
